name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - Main2  # Ensure this matches your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        source: "./"
        target: "/home/ubuntu/NAAVI-VERTICALLINE"

    - name: Execute SSH commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /home/ubuntu/NAAVI-VERTICALLINE
          pkill -f 'uvicorn main:app'
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > app.log 2>&1 &
